server:
  port: 8080
spring:
    datasource:
        name: root
        url: jdbc:mysql://192.168.31.54:3306/school
        username: root
        password: wuxiaobo000111
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      prefix: classpath:/templates/
      encoding: utf-8
      suffix: .html
    #spring配置缓存使用
    cache:
      type: redis
      cache-names: wuxiaobo
    redis:
      host: 192.168.31.54
      port: 6379
      password: wuxiaobo000111
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:xml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.bobo.springboot.lean.dao.entity  # 注意：对应实体类的路径